export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGS_FAILED = 'FETCH_INGS_FAILED';

export const PURCHASE_BURGER_SUCCCESS = 'PURCHASE_BURGER_SUCCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';